# Generated by Django 4.1 on 2023-02-26 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('nicknames', models.CharField(blank=True, max_length=200, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('religion', models.CharField(blank=True, max_length=100, null=True)),
                ('race', models.CharField(blank=True, max_length=100, null=True)),
                ('species', models.CharField(blank=True, max_length=100, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('birthplace', models.CharField(blank=True, max_length=200, null=True)),
                ('blood_type', models.CharField(blank=True, max_length=5, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('eye_colour', models.CharField(blank=True, max_length=50, null=True)),
                ('hair_colour', models.CharField(blank=True, max_length=50, null=True)),
                ('eyesight', models.CharField(blank=True, max_length=50, null=True)),
                ('dominant_hand', models.CharField(blank=True, max_length=20, null=True)),
                ('voice', models.CharField(blank=True, max_length=100, null=True)),
                ('physical_description', models.CharField(blank=True, max_length=2000, null=True)),
                ('clothing', models.CharField(blank=True, max_length=2000, null=True)),
                ('medical_history', models.CharField(blank=True, max_length=2000, null=True)),
                ('criminal_record', models.CharField(blank=True, max_length=2000, null=True)),
                ('education', models.CharField(blank=True, max_length=2000, null=True)),
                ('forming_events', models.CharField(blank=True, max_length=2000, null=True)),
                ('romance', models.CharField(max_length=2000, null=True)),
                ('relationships', models.CharField(max_length=2000, null=True)),
                ('employment', models.CharField(max_length=2000, null=True)),
                ('pets', models.CharField(blank=True, max_length=2000, null=True)),
                ('hopes_and_dreams', models.CharField(max_length=2000, null=True)),
                ('fears', models.CharField(max_length=2000, null=True)),
                ('hobbies', models.CharField(max_length=2000, null=True)),
                ('likes', models.CharField(max_length=2000, null=True)),
                ('dislikes', models.CharField(max_length=2000, null=True)),
                ('personality', models.CharField(max_length=2000, null=True)),
                ('skills', models.CharField(blank=True, max_length=3000, null=True)),
                ('weaknesses', models.CharField(blank=True, max_length=3000, null=True)),
            ],
        ),
    ]
