# Generated by Django 4.1 on 2023-02-27 01:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_character_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='created',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
        ),
    ]
