# Generated by Django 4.1 on 2023-02-27 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0005_delete_containedin'),
        ('characters', '0003_character_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='folders.folder'),
        ),
    ]
