# Generated by Django 4.1 on 2023-02-28 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0006_character_tags_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='tags',
        ),
    ]
