# Generated by Django 4.1 on 2023-03-02 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0007_remove_character_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
