# Generated by Django 4.1 on 2023-03-02 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0008_character_private'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='dominant_hand',
            new_name='handedness',
        ),
    ]
