# Generated by Django 4.1 on 2023-03-11 00:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0011_alter_folder_created'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('characters', '0009_rename_dominant_hand_character_handedness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='folders.folder'),
        ),
        migrations.AlterField(
            model_name='character',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
