# Generated by Django 4.1 on 2023-02-26 22:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0002_folder_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='created',
            field=models.TimeField(auto_created=True, default=django.utils.timezone.now),
        ),
    ]
