# Generated by Django 4.1 on 2023-03-02 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0007_alter_folder_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
