# Generated by Django 4.1 on 2023-03-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0008_folder_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
