# Generated by Django 4.1 on 2023-03-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0009_folder_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
